apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: api-example-com
  namespace: default
  labels:
    app: apis
    extauth: basic
spec:
  parentRefs:
    - name: gw
      namespace: ingress-gw
  hostnames:
    - "api.example.com"
  rules:
    - matches:  
      - path:
          type: RegularExpression
          # Match http://api.example.com/v1/{status-code}/status
          value: ^\/v1\/\d{3}\/status$
      backendRefs:
      - name: httpbin
        namespace: httpbin
        port: 8000